### ISSUE TITLE
Allow setting CAN_RAW_RECV_OWN_MSGS

### ISSUE THREAD

**Issue by Kheirlb** [sebi2k1/node-can#113]
Something that would be useful to set in node-can is CAN_RAW_RECV_OWN_MSGS when creating a RawChannel. This will make prototyping a little bit easier. See [python-can](https://github.com/hardbyte/python-can) for reference `can.interface.Bus(receive_own_messages=True)`.

**Comment by sebi2k1** [comment]
The idea was to create just another RawChannel to get closer to real world use case.
