### ISSUE TITLE
npm install socketcan fails

### ISSUE THREAD

**Issue by magnussp** [sebi2k1/node-can#12]
Hi!

While trying to install via npm install socketcan it fails for me.
I updated to latest nodejs but still didn't help.

I noticed that it during the install complained that it couldn't find the module nan. So I did a npm install nan and after that the npm install socketcan worked.

Could it be that you have forgotten to add nan in the package.json I can only see it under devDependencies and not dependencies. But I'm not to good with how these package.json files work.

**Comment by sebi2k1** [comment]
Hi!

I'm going to check this on the weekend. Till now I thought in is sufficient to add nan to the devDependencies. At least this was done in the example I used.

/Sebastian

**Comment by sebi2k1** [comment]
Pushed a new version which should fix the dependency issue.
