### ISSUE TITLE
Seems not to work with node-js 22

### ISSUE THREAD

**Issue by MyHomeMyData** [sebi2k1/node-can#136]
I'm using socketcan in ioBroker adapter [e3oncan](https://github.com/MyHomeMyData/ioBroker.e3oncan). Now I added node-js 22.x to the test-matrix. Test fails for socketcan, pls. have a look to the log:
https://github.com/MyHomeMyData/ioBroker.e3oncan/actions/runs/10885244181/job/30202383332

According to user ioBroker-Discord of ioBroker Telegram channel it seems to be a referencing problem to nan.h
nan 2.20 includes support for node 22, but referenced is nan 2.19 which does not support node 22.

**Comment by juleq** [comment]
From what I see it looks like an issue upstream:

https://github.com/nodejs/nan/issues/936

Could be wrong but there are suggestions to a workaround you could try to confirm.

**Comment by MyHomeMyData** [comment]
When I clone `node-can` and do a `npm ci` it fails due to a problem within `nan.h`.

The cause seems to be a reference to **nan version 2.17.0** in `package-lock.json`.

After changing `"nan": "*"` to `"nan": ">=2.21.0"` in `package.json` and `npm install` now `npm ci` runs without error.

Would you please check?

**Comment by sebi2k1** [comment]
Thanks for the hint. Tested it and fixed with 4.0.5.
