### ISSUE TITLE
Not parseing consumers correctly

### ISSUE THREAD

**Issue by zorce** [sebi2k1/node-can#20]
According to the KCD specification [here](https://github.com/dschanoeh/Kayak/blob/master/Kayak-kcd/src/main/resources/com/github/kayak/canio/kcd/loader/Definition.xsd) the consumer is part of the signal not the message itself. Therefor parsing of consumers is not done correctly.

**Comment by sebi2k1** [comment]
You are right. Working on a fix now.

**Comment by sebi2k1** [comment]
Fixed in e5626033b384ef47223fb7adab84cd70d049eb77.

**Comment by zorce** [comment]
Nice! Will try it out.
