### ISSUE TITLE
How to create obervables using channel.addListener?

### ISSUE THREAD

**Issue by daixtrose** [sebi2k1/node-can#24]
Hi!

I would like to create observables for `channel.addListener('onMessage', cb)`. Do you have some example code? Mine failed silently

```javascript
var observableMessages = Rx.Observable.fromEvent(channel.onMessage);

var subscription = observableMessages.subscribe((msg) => {
    ...
});
````

**Comment by sebi2k1** [comment]
Sorry, don't have a clue. I leave it open, maybe somebody else can help.

**Comment by daixtrose** [comment]
My current solution is (using latest RxJS version):

```javascript
var Rx = require('rxjs/Rx');
...
var observableMessages = Rx.Observable.create(obs => {
    let cb = function(msg) { obs.next(msg); };
    channel.addListener("onMessage", cb);
    return function() {
	// See #25
	// channel.removeListener(cb);
    }
});

var subscription = observableMessages.subscribe((msg) => {
    console.log(msg);
    ...
});


```

**Comment by daixtrose** [comment]
Note that this solution is not compatible with Rx rules as long as `removeListener` is unavailable. If someone calls `subscription.dispose()` the events will still get through, which is disallowed behaviour.

There are 2 possibilities to cure this:
- refine the above solution to maintain state and disable `obs.netx(msg)` in case of an unsubscription
- add `removeListener` as method to `RawChannel`

**Comment by daixtrose** [comment]
Current conforming solution:

```javascript
var observableMessages = Rx.Observable.create(obs => {
    let active = true;
    let cb = function(msg) {
	if (active) {
	    obs.next(msg);
	}
    };
    
    channel.addListener("onMessage", cb);

    return function() {
	active = false;
    }
});
```

**Comment by sebi2k1** [comment]
Ok, we will add removeListener.

**Comment by daixtrose** [comment]
I'd prefer to keep the issue open until the method is added.
