### ISSUE TITLE
Message update on no value signals

### ISSUE THREAD

**Issue by Flycode-1** [sebi2k1/node-can#28]
Hi !

**Following the example to update and send a message :** 

```
// Update tank temperature
db.messages["TankController"].signals["TankTemperature"].update(80);

// Trigger sending this message
db.send("TankController");
```

**How could I send a message that as no value that would be defined such as the following in a kcd file :** 

```
<Message id="0x00A" name="Airbag">
		 	<Producer>
		 		<NodeRef id="2"/>
		 	</Producer>
		 	<Signal name="DriverAirbagFired" offset="0"/>
		 	<Signal name="CodriverAirbagFired" offset="1"/>
		 	<Signal name="DriverSeatOccupied" offset="2"/>
		 	<Signal name="CodriverSeatOccupied" offset="3"/>
		 	<Signal name="DriverSeatbeltLocked" offset="4"/>
		 	<Signal name="CodriverSeatbeltLocked" offset="5"/>
		 	<Signal name="AirbagConfiguration" offset="8" length="8"/>
		 	<Signal name="SeatConfiguration" offset="16" length="8"/>
		 </Message>
```

How to update and send such message if i want to send for example the signal "DriverSeatOccupied" ?
`db.messages["Airbag"].signals["DriverSeatOccupied"].update(??);`
Many thanks for your help!

**Comment by sebi2k1** [comment]
I don't get the question, you can send a message defined in the database via db.send, in your case: 
db.messages["Airbag"].signals["DriverSeatOccupied"].update(xx);
db.send("Airbag")

**Comment by Flycode-1** [comment]
Hi Sebastian thank you for you quick response.

I am glad to know this is something possible.What is the xx parameter in
send in this case ?

db.messages["Airbag"].signals["DriverSeatOccupied"].update(*xx*);
db.send("Airbag")

kind regards,

2017-02-08 7:42 GMT+01:00 Sebastian <notifications@github.com>:

**Comment by sebi2k1** [comment]
XX is the value of the signal in the message.

**Comment by corn3lius** [comment]
FYI : 

https://github.com/sebi2k1/node-can/blob/master/parse_kcd.js#L178

the length on your signal is defaulted to 1 bit so the only values you can code are ( 0|1)

**Comment by Flycode-1** [comment]
Thanks for your help , this works perfectly. 
Again congratulation for this NodeJS SocketCAN extension, it is a very handy extension !
