### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by Vladyslav93** [sebi2k1/node-can#31]
Is it possible in perspective or now use CAN on the windows machine?

**Comment by sebi2k1** [comment]
This is highly unlikely since each vendor uses its own proprietary APIs and DLLs on Windows platform.

**Comment by dogmatic69** [comment]
You might have some luck using Windows 10 with its built in [linux subsystem](https://msdn.microsoft.com/en-gb/commandline/wsl/install_guide).

**Comment by Vladyslav93** [comment]
@sebi2k1 I case if I have DLL for Windows, how to implement him to node-red? Is it hard? Do you have some example? I will be so appreciated. Thanks.

**Comment by sebi2k1** [comment]
DLL is not enough. You need a RawChannel implementation. Once you have it you can implement node-red connection. But never tried it, sorry.
