### ISSUE TITLE
Can Send

### ISSUE THREAD

**Issue by FatherNelson** [sebi2k1/node-can#33]
I am a rookie at this CAN bus stuff, and in the process I was attempting to create a program similar to cansend in can-utils with this extension. I was able to get a reply message as the example program shows, but have not yet found a way to send my own hex value through the function, or find a way to hard code a value to make sure that it is working. Any help to do this would be greatly appreciated.

**Comment by sebi2k1** [comment]
Just sending a CAN message?
```
var canmsg = { id: 10, data: new Buffer([ 0, 0xFF, 0xFE, 0xFD, 0xFC, 0xFB, 0xFA, 0xF7 ]) };
channel.send(canmsg);
```
