### ISSUE TITLE
"TypeError: msg.payload.indexOf is not a function"

### ISSUE THREAD

**Issue by Vladyslav93** [sebi2k1/node-can#35]
Hello, I have this issue as on the picture below:

![image](https://user-images.githubusercontent.com/28342273/27117573-7101cb74-50d7-11e7-8ebb-94be425471e7.png)

I am trying to send the Data "4000100000000000" to CAN ID "00", but got this error. Some ideas?

Thanks

**Comment by sebi2k1** [comment]
Sorry, never tried node-can with node-red.
