### ISSUE TITLE
64 bit

### ISSUE THREAD

**Issue by at30in** [sebi2k1/node-can#36]
64 bit signal not working because use int 32 bit.
in signal.cc work around for method _setvalue

uint64_t m = ~0 & ~(1ULL << bitLength);
    if (bitLength == 64) 
    {
        m = ULLONG_MAX;
    }

but for NAN_METHOD(DecodeSignal) I don't know.....

**Comment by sebi2k1** [comment]
Actually values >32bit are not intended to be supported at all. ;-)

Anyhow how will look into supporting them. For your use case (64bit) you might just convert the whole payload to a number.
