### ISSUE TITLE
Example code fails - Cannot read property 'signals' of undefined

### ISSUE THREAD

**Issue by tmlbl** [sebi2k1/node-can#41]
I am running the example from the README and running into an issue.

It looks like the code is expecting `db.messages` to be a map, but mine is a long array with many null fields, and the message descriptions as JSON objects in the array. It appears to be an issue with the parser, since I can get the example working by doing the following (excuse the `this` as this is in a class method):

```javascript
this.network = can.parseNetworkDescription(
    "node_modules/socketcan/samples/can_definition_sample.kcd");
this.channel = can.createRawChannel("vcan0");
this.db = new can.DatabaseService(
    this.channel, 
    this.network.buses['Motor']
);
this.channel.start();

this.db.messages.find(m => m && m.name == 'Emission')
    .signals['Enginespeed'].onUpdate(s => {
        console.log('Enginespeed', s.value);
    });

this.db.messages.find(m => m && m.name == 'Emission')
    .signals['Enginespeed'].update(80);
```

But obviously this is not the intended API.

**Comment by sebi2k1** [comment]
You are right. The example had an issue, the TankController is on instrumentation bus and the db object on motor bus. I fixed the example.
