### ISSUE TITLE
Message Filters

### ISSUE THREAD

**Issue by captain1991cv** [sebi2k1/node-can#53]
Hi,
I'm trying to design a web interface to control canBus using mcp2515. now, i need to set  a filter for incoming data which is chosen by user in run time. is there any way to  set  filters without involving into kcd? if there is none, how should i change kcd in run time? can anyone do me a favor and post an example?

**Comment by sebi2k1** [comment]
Sure you, can use SetRxFilters on the channel, it configures the filter based on bit mask directly on kernel level.
