### ISSUE TITLE
Multiplexing limitation: Current restrictions to the multiplexor.

### ISSUE THREAD

**Issue by juleq** [sebi2k1/node-can#56]
The current implementation is a simplification of the Simple Signal Multiplexing described [here](https://assets.vector.com/cms/content/know-how/_application-notes/AN-ION-1-0521_Extended_Multiplexing_in_DBC_Databases.pdf).

It is simplified in that the multiplexor signal is assumed to be in the first byte of the payload. The multiplexor signal should be as flexible in positioning and length as any other signal. Further, I think its value can also be of one of the usual four suspects (signed/unsigned/single/double).

**Comment by sebi2k1** [comment]
Fixed in f2a547b794c7a79d02d6dc170c252d10d9fe8816

As per KCD file the type is always unsigned.
