### ISSUE TITLE
Extended frames example

### ISSUE THREAD

**Issue by brandonros** [sebi2k1/node-can#61]
I have the following:

```
Request:

`cansend can0 7E0#0322F12100000000`

Response:

$ candump -L can0 | grep '7E8#'
(1555792813.746362) can0 7E8#037F2278AAAAAAAA
(1555792813.832389) can0 7E8#102162F121313737
```

Would I need to send the response as 2 messages to the channel? Note how the length byte on the second message is `0x10`, which is greater than `0x08` (aren't all CAN messages supposed to be 0x08 bytes long)?

**Comment by sebi2k1** [comment]
The first byte in the frames are related to your protocol and not to CAN itself. The limitation of 8 bytes (CAN2.0B) is on layer 2. You are using a protocol which segments bigger payloads by introducing a dedicated length byte.
