### ISSUE TITLE
Debugging `err: true` on a lot of messages

### ISSUE THREAD

**Issue by brandonros** [sebi2k1/node-can#62]
How can I trace back what is causing so many CAN bus errors?

**Comment by sebi2k1** [comment]
CAN bus errors are caused physical errors on the bus and the answer depends on your topology, i would recommend too:
1. Take a multi meter and measure the resistance between CAN_H and CAN_L. Should be around 60Ohm typically (both ends of the bus should be terminated with 120Ohm each).
2. Check your bus topology. CAN is a bus and the actual wiring should be a bus as well. Stub lines from the main branch shouldn't be longer than 80cm typically w/o additional repeaters.
2. If resistance and topology is fine, disconnect node by node. Node might have a physical defect or the bit timing may be off or any other issue.
