### ISSUE TITLE
Change 'associative array' to Object or other Datatype

### ISSUE THREAD

**Issue by team-p5x** [sebi2k1/node-can#64]
In socketcan.js you are using a associative array for the signals. Why don't you use it as a normal array or why don't you use a Object?

`/**
         * Named array of signals within this message. Accessible via index and name.
         * @attribute {Signal} signals
         * @final
         */
	this.signals = [];

	for (i in desc['signals']) {
		var s = desc['signals'][i];
		if (this.signals[s.name] && this.signals[s.name].muxGroup) {
			this.signals[s.name].muxGroup.push(s.mux);
		} else {
			this.signals[s.name] = new Signal(s);
		}
	}`

**Comment by sebi2k1** [comment]
Sorry for the late reply, just back form vacation. I am not sure what you are actually proposing? What is the disadvantage from your side using an associative array?

**Comment by sebi2k1** [comment]
Feel free to make a pull request, may be I understand better then what you are trying to enhance.
